version: '3.8'

services:
  gabaithon-grpc-server:
    container_name: gabaithon-grpc-server
    volumes:
      - ./:/gabaithon-grpc-server
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    command: sh -c 'air'